In [108]:
# !pip install xgboost

In [109]:
import sys
print(sys.executable)

C:\Users\debas\AppData\Local\Programs\Python\Python311\python.exe

In [110]:
# C:\Users\debas\.conda\envs\multiflow_env\python.exe -m pip install xgboost

In [111]:
# C:\Users\debas\AppData\Local\Programs\Python\Python311\python.exe -m pip install mlflow

In [112]:
# import sys
# !{sys.executable} -m pip install mlflow   # The True Error less Code

In [113]:
# import sys
# !{sys.executable} -m pip install dagshub

In [114]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.svm import SVR

from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from xgboost import XGBRegressor

import mlflow

In [115]:
# set the dagshub tracking server 
mlflow.set_tracking_uri("https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow")

In [116]:
import dagshub
dagshub.init(repo_owner='Dev-debasish-09', repo_name='uber-demand-prediction', mlflow=True)

Initialized MLflow to track repo "Dev-debasish-09/uber-demand-prediction"

Repository Dev-debasish-09/uber-demand-prediction initialized!

In [117]:
# load train and test data 
train_data_path = "C:\\Users\\debas\\Uber demand Prediction/Data/train.csv"
test_data_path = "C:\\Users\\debas\\Uber demand Prediction/Data/train.csv"

train_df = pd.read_csv(train_data_path,parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")
test_df = pd.read_csv(test_data_path,parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")

train_df

,lag_1,lag_2,lag_3,lag_4,region,total_pickups,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,187,161.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,194,175.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,180,177.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,197,185.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185,185.0,4
...,...,...,...,...,...,...,...,...
2016-02-29 22:45:00,15.0,9.0,11.0,11.0,29,12,12.0,0
2016-02-29 23:00:00,12.0,15.0,9.0,11.0,29,17,14.0,0
2016-02-29 23:15:00,17.0,12.0,15.0,9.0,29,15,14.0,0
2016-02-29 23:30:00,15.0,17.0,12.0,15.0,29,15,15.0,0
2016-02-29 23:45:00,15.0,15.0,17.0,12.0,29,12,14.0,0

In [118]:
# missing value in training data

train_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [119]:
# missing value in testing data 

test_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [120]:
# make x_train and y_train

x_train = train_df.drop(columns=["total_pickups"])

y_train = train_df["total_pickups"]

In [121]:
x_train.head()

,lag_1,lag_2,lag_3,lag_4,region,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,161.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,175.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,177.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,185.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185.0,4

In [122]:
y_train

tpep_pickup_datetime
2016-01-01 01:00:00    187
2016-01-01 01:15:00    194
2016-01-01 01:30:00    180
2016-01-01 01:45:00    197
2016-01-01 02:00:00    185
                      ...
2016-02-29 22:45:00     12
2016-02-29 23:00:00     17
2016-02-29 23:15:00     15
2016-02-29 23:30:00     15
2016-02-29 23:45:00     12
Name: total_pickups, Length: 172680, dtype: int64

In [123]:
# make X_test and y_test

x_test = test_df.drop(columns=["total_pickups"])

y_test = test_df["total_pickups"]

In [124]:
x_test.head()

,lag_1,lag_2,lag_3,lag_4,region,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,161.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,175.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,177.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,185.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185.0,4

In [125]:
from sklearn import set_config

set_config(transform_output = "pandas")

In [126]:
# encode the data 

encoder = ColumnTransformer([
    ("ohe",OneHotEncoder(drop = "first",sparse_output = False),["region","day_of_week"])
],remainder = "passthrough",n_jobs = -1 ,force_int_remainder_cols = False)

In [127]:
encoder

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['region', 'day_of_week'])])

In [128]:
# encode the train and test data

x_train_encoded = encoder.fit_transform(x_train)
x_test_encoded = encoder.transform(x_test)

In [129]:
# !pip install optuna

In [130]:
import optuna
import tqdm

In [131]:
import mlflow
import os

# # Force MLflow to store runs locally inside your repo
# repo_path = r"C:/Users/debas/Dev-debasish-09/uber-demand-prediction/mlruns"
# mlflow.set_tracking_uri(f"file:///{repo_path.replace(os.sep, '/')}")

# # Now you can safely set your experiment
# mlflow.set_experiment("Model Selection")

In [132]:
# set the experiment

mlflow.set_experiment("Model Selection")

2025/09/01 15:30:37 INFO mlflow.tracking.fluent: Experiment with name 'Model Selection' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/cefc21b938fe45dd84d45fa8b9e501e6', creation_time=1756720745481, experiment_id='0', last_update_time=1756720745481, lifecycle_stage='active', name='Model Selection', tags={}>

In [133]:
def objective(trial):
    # start the child run
    with mlflow.start_run(nested=True) as child:
        
        # model name search space
        list_of_models = ["LR", "RF", "GBR", "XGBR"]
        model_name = trial.suggest_categorical("model_name", list_of_models)
    
        if model_name == "LR":
            model = LinearRegression()
    
        elif model_name == "RF":
            n_estimators_rf = trial.suggest_int("n_estimators_rf",10,100,step=10)
            max_depth_rf = trial.suggest_int("max_depth_rf",3,10)
            model = RandomForestRegressor(n_estimators=n_estimators_rf, 
                                          max_depth=max_depth_rf, 
                                          random_state=42, n_jobs=-1)
    
        elif model_name == "GBR":
            n_estimators_gb = trial.suggest_int("n_estimators_gb",10,100,step=10)
            learning_rate_gb = trial.suggest_float("learning_rate_gb",1e-4,1e-1, log=True)
            model = GradientBoostingRegressor(n_estimators=n_estimators_gb, 
                                              learning_rate=learning_rate_gb,
                                             random_state=42)
    
        elif model_name == "XGBR":
            n_estimators_xgb = trial.suggest_int("n_estimators_xgb",10,100,step=10)
            learning_rate_xgb = trial.suggest_float("learning_rate_xgb",1e-4,1e-1, log=True)
            max_depth_xgb = trial.suggest_int("max_depth_xgb",3,10)
            model = XGBRegressor(n_estimators=n_estimators_xgb,
                                learning_rate=learning_rate_xgb,
                                max_depth=max_depth_xgb)
    
        # log the model name
        mlflow.log_param("model_name",model_name)
        
        # log the model parameters
        mlflow.log_params(model.get_params())
        
        # fit on the data
        model.fit(x_train_encoded,y_train)
    
        # get the predictions
        y_pred = model.predict(x_test_encoded)
    
        # calculate the loss
        loss = mean_absolute_percentage_error(y_test, y_pred)
    
        # log the metric
        mlflow.log_metric("MAPE",loss)
        return loss

In [134]:
# optimize the objective function

with mlflow.start_run(run_name="best_model", nested=True) as parent:

    # create a study object
    study = optuna.create_study(study_name="model_selection", direction="minimize")
    # optimize the objective function
    study.optimize(func=objective, n_trials=100, n_jobs=-1)
    
    # log the best parameters
    mlflow.log_params(study.best_params)
    # log the best error value
    mlflow.log_metric("Best_MAPE", study.best_value)

[I 2025-09-01 15:30:38,929] A new study created in memory with name: model_selection

🏃 View run industrious-seal-130 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/577ab7376abe4bfca3c5e662d7ef6a27
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:31:09,653] Trial 1 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run nosy-quail-888 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/e52973bd85a04693a88f53da1849733c
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run efficient-finch-772 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/606b2d073dea4610af7f118c2af6487c
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run selective-crow-985 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/91e7a9e652854f7fb3f37b5ecca819ef
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run selective-hen-817 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/339d4de9128d4bf18f0a39d4775036d5
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run stately-gnat-605 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/3130618cc7664599b98a450b21b6dc90
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run agreeable-dove-400 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/b9cbee889d1340bdbdac47370f1b6ccf
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run persistent-midge-8 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/a28bbea64a534e0cb07f0f85062953e4
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run rare-robin-176 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/b579ac68de4f46c9bbb9f0d56bde4ce3
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:31:55,629] Trial 0 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:31:56,667] Trial 7 finished with value: 0.12394048466555928 and parameters: {'model_name': 'RF', 'n_estimators_rf': 90, 'max_depth_rf': 9}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:31:57,676] Trial 12 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run melodic-toad-399 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/020fe1b3e9514e7e8c0ded2ec2cf1442
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:31:59,621] Trial 5 finished with value: 0.16023435790248938 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 7}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:32:00,615] Trial 6 finished with value: 0.2228505077179575 and parameters: {'model_name': 'RF', 'n_estimators_rf': 80, 'max_depth_rf': 5}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:32:02,694] Trial 3 finished with value: 5.188218593597412 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 20, 'learning_rate_xgb': 0.018106489400032368, 'max_depth_xgb': 4}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:32:03,717] Trial 9 finished with value: 6.014660358428955 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.02052350470067677, 'max_depth_xgb': 10}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:32:04,607] Trial 2 finished with value: 3.707526922225952 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 70, 'learning_rate_xgb': 0.010635734373888747, 'max_depth_xgb': 3}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:32:08,628] Trial 8 finished with value: 7.3438994120207335 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 40, 'learning_rate_gb': 0.00014829171729427898}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run bedecked-trout-806 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/d4190733262c4b0a9f9556740d9c6786
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:32:21,740] Trial 11 finished with value: 7.317460731238581 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 70, 'learning_rate_gb': 0.00013928293735462113}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run debonair-wolf-303 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/2352670d33e94549b466e12e7a968b74
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:32:56,655] Trial 10 finished with value: 0.2228505077179575 and parameters: {'model_name': 'RF', 'n_estimators_rf': 80, 'max_depth_rf': 5}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run learned-asp-842 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/a56028dabf804dd8a08c60d87528b3f8
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run sincere-stag-675 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/b0b6bc26e2224961b8d8ebe21a30edf3
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run omniscient-cub-4 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/22bb463f5dca4bd7a92de9b12cbe1dca
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run shivering-flea-537 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/e2e22847355b4001adf8c77c4232ee45
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run calm-skunk-201 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/4e4cd328701645ee8b261d95e9c33393
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run glamorous-stag-855 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/6dfa5159a794485c8c4cd220b578e8dd
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:33:16,625] Trial 4 finished with value: 6.258589851217324 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.0017596738398400278}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run luminous-moose-210 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/0cebdfc9443341d4bb45dd827cf06646
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:33:18,673] Trial 14 finished with value: 0.5721260251274246 and parameters: {'model_name': 'RF', 'n_estimators_rf': 40, 'max_depth_rf': 3}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run victorious-crow-823 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/6cc431f6dcf047e58aa936f5d95dc625
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:33:22,770] Trial 15 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:33:23,693] Trial 13 finished with value: 0.1599243702883762 and parameters: {'model_name': 'RF', 'n_estimators_rf': 90, 'max_depth_rf': 7}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:33:24,713] Trial 16 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:33:25,640] Trial 20 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:33:27,672] Trial 21 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:33:29,733] Trial 19 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run colorful-sponge-400 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/9691a42e4b544c3cab1e785e336139d7
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run thoughtful-jay-162 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/6ce30f6d15ba4476a643ea7fede2ae7a
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run orderly-stoat-507 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/e67f897c002d4f8597ea047c28b743bf
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:33:55,624] Trial 18 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:33:58,114] Trial 17 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:34:00,661] Trial 22 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run unleashed-seal-636 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/68278b40c0a346af9a25d2f83b697f76
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:34:21,645] Trial 23 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run amusing-foal-628 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/fce210732aa64d80adb5530caffbc501
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run sassy-shrew-156 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/6e950bbdd1734ff9987fe5b122b0d2f2
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run aged-dove-199 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/97b715e8b21b4362b7e5e23de86cc374
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run dashing-duck-126 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/d3edd0d77f884f97a29f80618cbf556e
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:34:42,639] Trial 26 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:34:43,589] Trial 25 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:34:44,690] Trial 28 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:34:49,603] Trial 31 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run treasured-fawn-978 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/c0c7ac20fdae47d1a2916121351a5c61
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run peaceful-fox-272 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/129f47c6ae374dc9940c88934dbc30d3
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run judicious-crow-470 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/298138a9db58401c93b72385013628bc
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:35:07,731] Trial 30 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run bright-flea-556 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/d98f1e5d593949f4b6195e1a1fbf279d
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run flawless-panda-60 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/2f5de302a8b44bfda61427efc3421201
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:35:15,610] Trial 32 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:35:16,633] Trial 29 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:35:18,693] Trial 33 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run tasteful-conch-668 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/85ebd5fef1dc4a81a4ca38f1b18db340
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:35:20,631] Trial 34 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:35:29,639] Trial 27 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run bemused-gnat-454 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/cfc07f3f272f4f2caa922f1a4f032171
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:35:41,621] Trial 24 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run lyrical-slug-130 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/f7eba67a07204d56a476d1e132cbcd13
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run gifted-crane-796 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/325176a4f29c407c8d0e2115c0c12a69
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run merciful-hare-98 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/6fa2006f429b433dab9cdb6d32bffdea
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run bustling-swan-153 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/cb8af0473cd54bbc843f60c5defb77ca
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:35:55,640] Trial 35 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:36:02,718] Trial 36 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:36:04,639] Trial 38 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run wise-doe-707 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/8136f06cda254ae0bf1241fae9f0a82d
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run abundant-hound-918 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/40c69305c9ad42beb7c88086f0b4260d
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:36:27,699] Trial 40 finished with value: 7.242214679718018 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.00019731208566245998, 'max_depth_xgb': 9}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run bemused-dog-525 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/1fdfb55eada048fa84d2c92c524e8d85
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:36:33,639] Trial 37 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:36:36,608] Trial 42 finished with value: 7.312502384185791 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 90, 'learning_rate_xgb': 0.00011088547885420742, 'max_depth_xgb': 9}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:36:38,656] Trial 43 finished with value: 7.298452377319336 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 90, 'learning_rate_xgb': 0.00013245959010226905, 'max_depth_xgb': 9}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run blushing-calf-834 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/1048272009e64cca9c1bcd0ec378ccef
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run learned-sow-344 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/073ae7d482694419ac28ed944f7ec7d2
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:36:59,650] Trial 44 finished with value: 7.280867099761963 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.00014357190103349364, 'max_depth_xgb': 9}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:37:00,630] Trial 46 finished with value: 7.263344764709473 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.00016789868149095108, 'max_depth_xgb': 9}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run defiant-trout-722 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/77bf9c8b8aee4a0e9c2ddbcdaafc2a4c
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run likeable-tern-689 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/562cc98591464f53953714dfe1c95d53
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run casual-conch-990 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/032480335e1f434880e970933814e8bc
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run blushing-horse-938 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/fb3995333adc483d98140a9bd4465c2a
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:37:15,623] Trial 39 finished with value: 7.31110954284668 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.00010172217372773169, 'max_depth_xgb': 9}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:37:22,603] Trial 47 finished with value: 7.269443988800049 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.00015942251558045953, 'max_depth_xgb': 9}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:37:23,720] Trial 48 finished with value: 7.3046488761901855 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.00011064710481892134, 'max_depth_xgb': 9}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run burly-ram-964 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/52727547e9714d49be417709e2e8f96d
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run fortunate-crab-677 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/cc6ac29cee9d438cb32d91041b697172
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run sassy-asp-8 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/b0c2696d840d4d11a8d54a438d391b24
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run skillful-lark-783 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/dffb2748d219467dba0cda792f210a14
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run delicate-skink-132 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/9e3d2316ea2d49829ebb4ab1d77ce39c
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:37:50,640] Trial 50 finished with value: 1.1571322180792991 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 20, 'learning_rate_gb': 0.09916137466905002}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:37:52,731] Trial 41 finished with value: 7.294576644897461 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.00012457857251814801, 'max_depth_xgb': 9}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:37:54,637] Trial 51 finished with value: 3.088809480251404 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.09119555013837687}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:37:55,664] Trial 49 finished with value: 7.306760311126709 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.00010771789669467142, 'max_depth_xgb': 10}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:37:57,605] Trial 52 finished with value: 3.1133726226268137 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.09007704750607401}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:37:59,746] Trial 53 finished with value: 3.7127395482449184 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.07188597243301552}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run rare-fish-474 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/3e1f00f117404ddaa5fe01b577aecdbf
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run worried-wolf-87 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/2c9cee807deb4db483a50b81df2273cc
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:38:21,673] Trial 55 finished with value: 3.5141555723932356 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.07774412760390054}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:38:23,728] Trial 54 finished with value: 0.10940366675772727 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 10}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run chill-vole-838 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/07937012bca34d0088627cf08030d775
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run dapper-kit-562 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/749af3b37da0465c923f0be197e59b42
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:38:37,642] Trial 45 finished with value: 7.308284282684326 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.0001056223225192299, 'max_depth_xgb': 9}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run lyrical-bat-574 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/1ae45a4300324ea4b7bc48a17e2942e0
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run rebellious-rat-82 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/46e8f55d72c4499ca1c6a8fddbb89b81
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:38:46,607] Trial 58 finished with value: 3.604576624321629 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.07466190260155697}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:38:49,727] Trial 57 finished with value: 3.2132338332440424 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.08684117705968215}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:38:52,598] Trial 56 finished with value: 4.685920844505608 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.04772548195684591}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run fun-whale-902 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/17a0cab873804ab7b7374848058af2e9
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run illustrious-pug-69 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/33ac1e3e86654e03a91e2900bbf219b2
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run kindly-sloth-901 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/22c95bfb89a0452b9a8a6ff20fbe3548
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:39:15,635] Trial 59 finished with value: 0.109526397976009 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 10}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run wise-cow-517 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/88aa6d05168247d1bfc10c4b86104c6f
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:39:17,659] Trial 63 finished with value: 0.109526397976009 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 10}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:39:20,653] Trial 62 finished with value: 0.109526397976009 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 10}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run blushing-bug-413 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/6e386fc3d1fa447f84e6b34872754950
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:39:26,594] Trial 60 finished with value: 0.109526397976009 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 10}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run luminous-skink-770 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/6abf6fa3dba14bf6af0cded41ce09528
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:39:34,609] Trial 64 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run traveling-donkey-473 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/e18cd7fc7ec247418767bc56da3364a9
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:39:41,644] Trial 65 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:39:48,609] Trial 66 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run stylish-quail-908 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/9b03f70be9cf4151809f49ee29f622aa
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run amusing-toad-430 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/cb750536deb64f3db4c69d8d1e352065
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run fortunate-ant-531 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/6a6157229af1453194990860bf1c7f0e
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:40:12,666] Trial 67 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:40:19,634] Trial 61 finished with value: 0.109526397976009 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 10}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:40:23,625] Trial 70 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run nebulous-shad-788 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/92c6488066bd4066a4610283bdb1770f
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run ambitious-kit-395 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/344742b64864445fa6205fe5b9e3d3f5
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run adorable-fox-816 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/3a97a206293f4858932892c28e46fe88
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:40:35,603] Trial 71 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run painted-skink-862 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/5034f9ea8ef64a02930b2ac7da5928da
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:40:40,614] Trial 73 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:40:41,648] Trial 69 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run powerful-ant-604 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/77717ad2b4564d60b921d5c8d8e48202
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:40:46,674] Trial 74 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run respected-duck-102 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/f93a6f5dee40461aaf055a68150fa3b5
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run beautiful-croc-553 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/3f581ff9a55c403883722a4b94ac656b
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:40:57,566] Trial 72 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:40:58,657] Trial 68 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:41:09,577] Trial 75 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run sedate-rook-573 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/78c573e028a9467491cf105d027b49c7
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:41:24,656] Trial 77 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run monumental-crab-76 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/b671b71eb5cd430eb1c2ed9df48359f9
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run serious-skunk-546 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/e1878ad608304aa8a5305a6099b189d6
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:41:37,661] Trial 78 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:41:43,699] Trial 80 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run selective-fowl-260 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/bb92ba2bcdf84ba9a9c3c7b8b6e99e57
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run unequaled-hog-937 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/f2e9c532806141d8b6dcf815bde17cc9
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run invincible-wren-802 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/10f1a054b58a4241a62e78074cd56d58
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:41:55,684] Trial 79 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:42:00,700] Trial 82 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run dapper-stork-216 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/357574b3ffd34b1e8afceed3390a6e0a
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:42:02,619] Trial 81 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run casual-sloth-461 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/259fc2106757443ea607573d5a641850
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run welcoming-kit-983 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/8f6f1c43112b475083faa5c6cd105421
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:42:11,657] Trial 84 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:42:16,664] Trial 83 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:42:18,630] Trial 86 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run colorful-rook-55 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/e0a3e610b6b6400eba5eb44669e8e955
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:42:29,682] Trial 87 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run nebulous-bug-950 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/1930a3e9c0de47dc90a6146cb2efe2fd
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run unruly-smelt-321 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/9e27f64c1d304655b73e7816237d4b1d
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:42:53,639] Trial 85 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run ambitious-rat-85 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/7d53591b5ec14f43b9fb2c7c9b514481
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:42:57,600] Trial 89 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:43:04,598] Trial 90 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run powerful-crow-126 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/28a895c47cc0421e9f9a8396d5366321
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run kindly-owl-832 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/01edbfc957324b46b0c37290bb7b5182
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:43:14,633] Trial 88 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run rogue-ram-570 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/4c8adae7fbaa4e288b0901e2403657a5
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run selective-snipe-2 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/6bfa17b186044140aa940fdc515d9275
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run auspicious-moth-279 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/52053f75264a4ceba8cff39a0e39b14f
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:43:22,573] Trial 93 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:43:24,657] Trial 92 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run colorful-hawk-874 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/55183681c95a4b61958047490202ab27
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run legendary-yak-958 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/b8ea829d95864a20bc079489e6f052dc
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:43:29,586] Trial 91 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:43:30,607] Trial 94 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:43:32,655] Trial 95 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:43:34,601] Trial 96 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run gaudy-swan-318 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/2ad69156574a4808b1e7b50685d75e74
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:43:38,594] Trial 97 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run kindly-dove-258 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/59607f81743d49a7b297452c5c17cd46
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run clumsy-carp-854 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/9c0b8ee1a0a14e2d8ee04833749bc34a
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:43:43,610] Trial 98 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.
[I 2025-09-01 15:43:44,640] Trial 99 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run valuable-ape-410 at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/9b16f46775284c2db765be4b59c26723
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

[I 2025-09-01 15:44:14,128] Trial 76 finished with value: 0.08778013304566522 and parameters: {'model_name': 'LR'}. Best is trial 1 with value: 0.08778013304566522.

🏃 View run best_model at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0/runs/1f4fe927c1df441b8c5e113735f35665
🧪 View experiment at: https://dagshub.com/Dev-debasish-09/uber-demand-prediction.mlflow/#/experiments/0

In [135]:
study.best_value

0.08778013304566522

In [136]:
# best parameters

study.best_params

{'model_name': 'LR'}

In [137]:
# model value counts

study.trials_dataframe()['params_model_name'].value_counts()

params_model_name
LR      63
XGBR    14
RF      12
GBR     11
Name: count, dtype: int64

In [138]:
from optuna.visualization import (
    plot_optimization_history, 
    plot_parallel_coordinate, 
    plot_param_importances
)

In [139]:
plot_optimization_history(study)

In [140]:
plot_parallel_coordinate(study, params=["model_name"])

In [141]:
# train the linear regression model

lr = LinearRegression()

lr.fit(x_train_encoded, y_train)

# get predictions
y_pred_train = lr.predict(x_train_encoded) 
y_pred_test = lr.predict(x_test_encoded)

# loss

mape_train = mean_absolute_percentage_error(y_train, y_pred_train)
mape_test = mean_absolute_percentage_error(y_test, y_pred_test)

print("The training error is ", mape_train)
print("The test error is ", mape_test)

The training error is  0.08778013304566522
The test error is  0.08778013304566522

In [142]:
lr.coef_

array([-2.33737604,  0.71512405, -0.55601505, -1.25311068, -3.20463231,
       -0.86685973, -2.79925402, -3.62516859,  0.41386463, -2.9376376 ,
       -1.97624678, -3.75050442,  0.51806283, -2.54033388, -2.43297463,
        0.47632075,  0.61254786, -4.7417372 , -2.03077217, -1.26960984,
       -4.03690273, -2.08863167, -1.0414428 ,  0.73561736, -0.99999442,
       -0.85944985, -2.43098478,  0.67112238,  0.57385071, -0.11719951,
       -0.28045898, -0.37180749, -0.5238324 , -0.4233113 , -0.34045774,
       -0.54170892, -0.36264553, -0.2493965 , -0.31905518,  2.4912456 ])

In [143]:
def tune_ridge(trial):
    # hyperparameter space
    alpha = trial.suggest_float("alpha",30,100)
    
    # make the model object
    ridge = Ridge(alpha=alpha, random_state=42)
    
    # train the model
    ridge.fit(x_train_encoded, y_train)
    
    # get predictions
    y_pred = ridge.predict(x_test_encoded)
    
    # calculate loss
    loss = mean_absolute_percentage_error(y_test, y_pred)

    return loss

In [144]:
# create study

study = optuna.create_study(study_name="tune_model", direction="minimize")

[I 2025-09-01 15:44:17,758] A new study created in memory with name: tune_model

In [145]:
# optimize

study.optimize(func=tune_ridge, n_trials=100, n_jobs=-1, show_progress_bar=True)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-09-01 15:44:18,204] Trial 0 finished with value: 0.08747009344521514 and parameters: {'alpha': 74.50896540693373}. Best is trial 0 with value: 0.08747009344521514.
[I 2025-09-01 15:44:18,341] Trial 1 finished with value: 0.08739488872277677 and parameters: {'alpha': 99.42091167119598}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,343] Trial 2 finished with value: 0.08749079157710062 and parameters: {'alpha': 68.19680631119674}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,375] Trial 3 finished with value: 0.08745997531494708 and parameters: {'alpha': 77.69279321173718}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,415] Trial 9 finished with value: 0.08742302896777865 and parameters: {'alpha': 89.75903193352147}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,425] Trial 7 finished with value: 0.08749318064757068 and parameters: {'alpha': 67.48263889397481}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,436] Trial 6 finished with value: 0.08750296707124472 and parameters: {'alpha': 64.58522907912196}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,436] Trial 4 finished with value: 0.08746291159131644 and parameters: {'alpha': 76.76422847443276}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,450] Trial 5 finished with value: 0.08747376448979606 and parameters: {'alpha': 73.3687208369165}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,452] Trial 8 finished with value: 0.08760985785862281 and parameters: {'alpha': 35.825577233289195}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,458] Trial 11 finished with value: 0.08750469321711735 and parameters: {'alpha': 64.07931924076338}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,466] Trial 10 finished with value: 0.08744245806190662 and parameters: {'alpha': 83.32688056687167}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,785] Trial 12 finished with value: 0.08751099409987861 and parameters: {'alpha': 62.24302570649706}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,808] Trial 13 finished with value: 0.08752101640656006 and parameters: {'alpha': 59.3645430645699}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,863] Trial 14 finished with value: 0.08741016493330096 and parameters: {'alpha': 94.1203378447285}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,899] Trial 16 finished with value: 0.08739750727101252 and parameters: {'alpha': 98.50301014979912}. Best is trial 1 with value: 0.08739488872277677.
[I 2025-09-01 15:44:18,925] Trial 15 finished with value: 0.08739423125247421 and parameters: {'alpha': 99.6519465129986}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:18,933] Trial 17 finished with value: 0.08740165435932964 and parameters: {'alpha': 97.05683322121573}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,016] Trial 18 finished with value: 0.08739510460267963 and parameters: {'alpha': 99.345075864947}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,028] Trial 22 finished with value: 0.0873958381898837 and parameters: {'alpha': 99.08757417335595}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,028] Trial 20 finished with value: 0.0874043944475499 and parameters: {'alpha': 96.10678936397748}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,044] Trial 19 finished with value: 0.08740073049246108 and parameters: {'alpha': 97.37786663178133}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,053] Trial 21 finished with value: 0.08740297666328536 and parameters: {'alpha': 96.59803365606975}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,212] Trial 24 finished with value: 0.08739502545833572 and parameters: {'alpha': 99.37287661316452}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,220] Trial 23 finished with value: 0.08739450665355811 and parameters: {'alpha': 99.55515810842668}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,275] Trial 25 finished with value: 0.08740355401433925 and parameters: {'alpha': 96.39792682192146}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,283] Trial 26 finished with value: 0.08754542893387023 and parameters: {'alpha': 52.533254582130326}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,375] Trial 27 finished with value: 0.08754452209175448 and parameters: {'alpha': 52.782329346799955}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,439] Trial 28 finished with value: 0.08743090558777727 and parameters: {'alpha': 87.12579303960489}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,446] Trial 29 finished with value: 0.08743231956805585 and parameters: {'alpha': 86.65739412624238}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,546] Trial 30 finished with value: 0.08742754116962743 and parameters: {'alpha': 88.24575839469378}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,550] Trial 31 finished with value: 0.08743197073789521 and parameters: {'alpha': 86.77287886402495}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,625] Trial 32 finished with value: 0.08742982943227295 and parameters: {'alpha': 87.48309627489587}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,632] Trial 34 finished with value: 0.08742922600129853 and parameters: {'alpha': 87.68388658301338}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,732] Trial 33 finished with value: 0.08753773479536026 and parameters: {'alpha': 54.657921720146064}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,742] Trial 35 finished with value: 0.08742816647783834 and parameters: {'alpha': 88.0368351586404}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,776] Trial 36 finished with value: 0.08742932456926579 and parameters: {'alpha': 87.65107770126241}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,868] Trial 37 finished with value: 0.08742849645610451 and parameters: {'alpha': 87.92680884017294}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,868] Trial 38 finished with value: 0.08743846197783404 and parameters: {'alpha': 84.63300964640466}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,969] Trial 39 finished with value: 0.08741894667266939 and parameters: {'alpha': 91.13609140029126}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,969] Trial 40 finished with value: 0.08741962122779147 and parameters: {'alpha': 90.90804948010891}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:19,975] Trial 41 finished with value: 0.08741623306043321 and parameters: {'alpha': 92.05477800587536}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,037] Trial 42 finished with value: 0.08741728862620401 and parameters: {'alpha': 91.69712921540167}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,061] Trial 43 finished with value: 0.08741599813528877 and parameters: {'alpha': 92.1344421400165}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,161] Trial 44 finished with value: 0.0874129129705587 and parameters: {'alpha': 93.18227674846472}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,263] Trial 47 finished with value: 0.08745083496775372 and parameters: {'alpha': 80.6102664481391}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,270] Trial 45 finished with value: 0.08744844018815333 and parameters: {'alpha': 81.3833458343725}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,288] Trial 46 finished with value: 0.08741442683297186 and parameters: {'alpha': 92.66761450025977}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,288] Trial 48 finished with value: 0.08741721788920863 and parameters: {'alpha': 91.72107908114053}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,288] Trial 49 finished with value: 0.08745235972642437 and parameters: {'alpha': 80.12018739510134}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,460] Trial 50 finished with value: 0.0874461299425916 and parameters: {'alpha': 82.13149256342662}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,461] Trial 52 finished with value: 0.08745203749193005 and parameters: {'alpha': 80.22366685494906}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,604] Trial 51 finished with value: 0.08745557598714253 and parameters: {'alpha': 79.09221686514408}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,604] Trial 53 finished with value: 0.08746167879512595 and parameters: {'alpha': 77.15356307612}. Best is trial 15 with value: 0.08739423125247421.
[I 2025-09-01 15:44:20,635] Trial 55 finished with value: 0.08739328982347784 and parameters: {'alpha': 99.98346245792231}. Best is trial 55 with value: 0.08739328982347784.
[I 2025-09-01 15:44:20,707] Trial 54 finished with value: 0.08745167433976515 and parameters: {'alpha': 80.34032922328367}. Best is trial 55 with value: 0.08739328982347784.
[I 2025-09-01 15:44:20,707] Trial 56 finished with value: 0.08739338523905192 and parameters: {'alpha': 99.94983935425927}. Best is trial 55 with value: 0.08739328982347784.
[I 2025-09-01 15:44:20,707] Trial 57 finished with value: 0.08747074799235717 and parameters: {'alpha': 74.30476568866447}. Best is trial 55 with value: 0.08739328982347784.
[I 2025-09-01 15:44:20,769] Trial 59 finished with value: 0.08746611584167083 and parameters: {'alpha': 75.7551947943179}. Best is trial 55 with value: 0.08739328982347784.
[I 2025-09-01 15:44:20,773] Trial 58 finished with value: 0.08747204357250207 and parameters: {'alpha': 73.9019686324799}. Best is trial 55 with value: 0.08739328982347784.
[I 2025-09-01 15:44:20,783] Trial 60 finished with value: 0.08747547427716353 and parameters: {'alpha': 72.84145727385126}. Best is trial 55 with value: 0.08739328982347784.
[I 2025-09-01 15:44:20,837] Trial 61 finished with value: 0.08739325736771568 and parameters: {'alpha': 99.99489988072378}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:20,933] Trial 62 finished with value: 0.08739625741777145 and parameters: {'alpha': 98.94058695277198}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,062] Trial 63 finished with value: 0.08739421474625364 and parameters: {'alpha': 99.65774850866676}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,066] Trial 64 finished with value: 0.08739534629342484 and parameters: {'alpha': 99.26019299617218}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,164] Trial 65 finished with value: 0.08739349514135028 and parameters: {'alpha': 99.91111388281755}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,169] Trial 66 finished with value: 0.08740545237754462 and parameters: {'alpha': 95.74093121365038}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,176] Trial 68 finished with value: 0.08739337653499786 and parameters: {'alpha': 99.95290645520265}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,180] Trial 67 finished with value: 0.08739347680497325 and parameters: {'alpha': 99.91757474846017}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,284] Trial 71 finished with value: 0.08740672235059918 and parameters: {'alpha': 95.30252465595505}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,297] Trial 69 finished with value: 0.08740783619226888 and parameters: {'alpha': 94.91913518295289}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,315] Trial 70 finished with value: 0.0874073407337957 and parameters: {'alpha': 95.08952972181017}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,315] Trial 74 finished with value: 0.08740752940463621 and parameters: {'alpha': 95.02460187559618}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,337] Trial 73 finished with value: 0.08739376307386872 and parameters: {'alpha': 99.81671592958801}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,372] Trial 75 finished with value: 0.08740659606600613 and parameters: {'alpha': 95.34605965717333}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,393] Trial 72 finished with value: 0.0873935986120644 and parameters: {'alpha': 99.87465715661538}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,484] Trial 76 finished with value: 0.08740705889509126 and parameters: {'alpha': 95.18655912985443}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,600] Trial 77 finished with value: 0.08761824636244801 and parameters: {'alpha': 33.79265549807413}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,730] Trial 78 finished with value: 0.08740742481908811 and parameters: {'alpha': 95.0605902828668}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,736] Trial 79 finished with value: 0.08740169757561181 and parameters: {'alpha': 97.04182477150214}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,765] Trial 80 finished with value: 0.08739953013454319 and parameters: {'alpha': 97.79624100635277}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,771] Trial 81 finished with value: 0.08762220474324996 and parameters: {'alpha': 32.84348803969695}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,830] Trial 82 finished with value: 0.08740085710572491 and parameters: {'alpha': 97.33385626441103}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,836] Trial 84 finished with value: 0.08760603879740415 and parameters: {'alpha': 36.76143519118428}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,842] Trial 85 finished with value: 0.0875845306464917 and parameters: {'alpha': 42.16116139544625}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,843] Trial 83 finished with value: 0.08739895761101196 and parameters: {'alpha': 97.99612871679913}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,892] Trial 86 finished with value: 0.08759621745094884 and parameters: {'alpha': 39.20268805029447}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,896] Trial 87 finished with value: 0.08739755499622373 and parameters: {'alpha': 98.48631552476687}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,936] Trial 88 finished with value: 0.08739828578742638 and parameters: {'alpha': 98.23081427533364}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:21,983] Trial 89 finished with value: 0.08739936472764265 and parameters: {'alpha': 97.85398041576588}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:22,050] Trial 90 finished with value: 0.08758685848408465 and parameters: {'alpha': 41.566262061516966}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:22,088] Trial 91 finished with value: 0.08739992546540276 and parameters: {'alpha': 97.65826776452306}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:22,159] Trial 92 finished with value: 0.08739432830103333 and parameters: {'alpha': 99.61783667270676}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:22,208] Trial 93 finished with value: 0.08742266096907826 and parameters: {'alpha': 89.88284449289245}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:22,208] Trial 94 finished with value: 0.08739344177068446 and parameters: {'alpha': 99.92991937454318}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:22,208] Trial 95 finished with value: 0.08739334864719163 and parameters: {'alpha': 99.9627335662459}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:22,267] Trial 96 finished with value: 0.08739395889530274 and parameters: {'alpha': 99.7477346140628}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:22,271] Trial 97 finished with value: 0.08742210293239724 and parameters: {'alpha': 90.0706993347763}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:22,295] Trial 99 finished with value: 0.08742315313434444 and parameters: {'alpha': 89.71727364529775}. Best is trial 61 with value: 0.08739325736771568.
[I 2025-09-01 15:44:22,295] Trial 98 finished with value: 0.08742352101029534 and parameters: {'alpha': 89.59360171973228}. Best is trial 61 with value: 0.08739325736771568.

In [146]:
# best parameters

study.best_params

{'alpha': 99.99489988072378}

In [147]:
# best value

study.best_value

0.08739325736771568